# Generated by Django 6.0 on 2025-12-31 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='display_mode',
            field=models.CharField(choices=[('text', 'Text (Buttons)'), ('color', 'Color (Hex Code)'), ('image', 'Image (Pattern/Texture)')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='variationoption',
            name='color_code',
            field=models.CharField(blank=True, help_text='Hex code (e.g. #FF0000)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='variationoption',
            name='pattern_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.image'),
        ),
    ]
