# Generated by Django 6.0 on 2025-12-30 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('shop_email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sell_commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_vat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_shops', to='accounts.image')),
                ('logo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_shops', to='accounts.image')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['vendor'], name='vendors_ven_vendor__9ad084_idx'), models.Index(fields=['status'], name='vendors_ven_status_2259be_idx')],
            },
        ),
    ]
