# Generated by Django 6.0 on 2025-12-31 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_specific_images', to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active (Published)'), ('inactive', 'Inactive (Hidden)'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
