# Generated by Django 6.0 on 2025-12-30 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('initial', 'Initial Stock'), ('restock', 'Restock (Vendor Add)'), ('order', 'Order Deduction'), ('cancel', 'Order Cancellation (Restock)'), ('correction', 'Manual Correction'), ('return', 'Customer Return'), ('damage', 'Damaged/Lost')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive for addition, negative for deduction')),
                ('balance_after', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
