# Generated by Django 6.0 on 2025-12-30 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_platform_rate', models.BooleanField(default=True)),
                ('shipping_class', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express')], max_length=10)),
                ('delivery_time', models.CharField(max_length=255)),
                ('free_shipping_min_order', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('def_country_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='vendors.vendorshop')),
            ],
        ),
        migrations.CreateModel(
            name='WeightCostRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_calculation_method', models.CharField(choices=[('per_unit', 'Per Unit'), ('rules', 'Rules')], default='per_unit', max_length=10)),
                ('per_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_rule_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_rules', to='shipping.shippingrate')),
            ],
        ),
        migrations.CreateModel(
            name='WeightCostRuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_cost_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_items', to='shipping.weightcostrule')),
            ],
        ),
    ]
